
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Балансировщик нагрузки
  - job_name: 'load-balancer'
    static_configs:
      - targets: ['lb:80']
    metrics_path: '/stub_status'

  # Nginx экспортер 
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Docker контейнеры 
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
